# Generated by Django 2.2.4 on 2019-08-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isBlack',
            field=models.BooleanField(default=False),
        ),
    ]
