# Generated by Django 2.2.4 on 2019-08-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_customer_isblack'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassagerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cName',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cPhone',
            new_name='c_phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='isBlack',
            new_name='is_black',
        ),
        migrations.AddField(
            model_name='customer',
            name='line_id',
            field=models.CharField(default='tmp_id', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('c_name', models.CharField(max_length=10)),
                ('c_phone', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Massager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=10)),
                ('massagergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.MassagerGroup')),
            ],
        ),
    ]
